const MongoClient = require('mongodb').MongoClient;
// const assert = require('assert');
const url = 'mongodb://deza604-ferry-tracker-2-5483816:27017/ferrytracker';

const test = [ { name: 'Tsawwassen to Swartz Bay',
    sailingTime: '1 hour 35 minutes',
    date: '2018-05-06',
    '2018-05-06': 
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { name: 'Tsawwassen to Southern Gulf Islands',
    sailingTime: 'Variable',
    date: '2018-05-06',
    '2018-05-06': [ [Object], [Object], [Object], [Object], [Object] ] },
  { name: 'Tsawwassen to Duke Point',
    sailingTime: '2 hours',
    date: '2018-05-06',
    '2018-05-06': [ [Object], [Object], [Object], [Object], [Object], [Object] ] },
  { name: 'Swartz Bay to Fulford Harbour (Saltspring Is.)',
    sailingTime: '35 minutes',
    date: '2018-05-06',
    '2018-05-06': 
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { name: 'Swartz Bay to Southern Gulf Islands',
    sailingTime: 'Variable',
    date: '2018-05-06',
    '2018-05-06': [ [Object], [Object], [Object], [Object], [Object], [Object] ] },
  { name: 'Swartz Bay to Tsawwassen',
    sailingTime: '1 hour 35 minutes',
    date: '2018-05-06',
    '2018-05-06': 
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { name: 'Duke Point to Tsawwassen',
    sailingTime: '2 hours',
    date: '2018-05-06',
    '2018-05-06': [ [Object], [Object], [Object], [Object], [Object], [Object] ] },
  { name: 'Departure Bay to Horseshoe Bay',
    sailingTime: '1 hour 40 minutes',
    date: '2018-05-06',
    '2018-05-06': 
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { name: 'Horseshoe Bay to Snug Cove (Bowen Is.)',
    sailingTime: '20 minutes',
    date: '2018-05-06',
    '2018-05-06': 
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { name: 'Horseshoe Bay to Departure Bay',
    sailingTime: '1 hour 40 minutes',
    date: '2018-05-06',
    '2018-05-06': 
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { name: 'Horseshoe Bay to Langdale',
    sailingTime: '40 minutes',
    date: '2018-05-06',
    '2018-05-06': 
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { name: 'Langdale to Horseshoe Bay',
    sailingTime: '40 minutes',
    date: '2018-05-06',
    '2018-05-06': 
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] } ]

MongoClient.connect(url, function(err, db) {
    if (err) throw err;
    console.log('working');
    db.close();
});

